<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Clan;
use Doctrine\ORM\EntityRepository;

/**
 * ClanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanRepository extends EntityRepository
{
    public function getClanFromArray($data)
    {
        $clan = new Clan();

        $clan->setId($data->clan_id);
        $clan->setTag($data->tag);
        $clan->setName($data->name);
        $clan->setMembersCount($data->members_count);
        $clan->setLastUpdated(new \DateTime('now'));
        $clan->setLastEventUpdateDate(new \DateTime('now'));

        return $clan;
    }
}
