<?php

namespace AppBundle\Repository;

use AppBundle\Entity\EventAccountData;
use Doctrine\ORM\EntityRepository;

/**
 * EventAccountDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAccountDataRepository extends EntityRepository
{
    /*
     * parses $mdata to add them as collection to $clan
     */
    public function setClanMembersFromArray(&$clan, $mdata)
    {
        if (count($mdata))
        {
            foreach($mdata as $m)
            {
                $ad = new EventAccountData();
                $ad->setAccountId($m['account_id']);
                $ad->setAccountName($m['account_name']);
                $d = new \DateTime();
                $d->setTimestamp($m['joined_at']);
                $ad->setJoinedAt($d);
                $ad->setClan($clan);

                $clan->addMember($ad);
            }
        }
    }

    /*
 * parses $eventinfo to fields
 */
    public function setEventDataFromArray(&$ad, $m)
    {
        $ad->setEvent(key($m));
        $m = $m[key($m)][0];
        $ad->setAwardLevel($m['award_level']);
        $ad->setBattles($m['battles']);
        $ad->setRank($m['rank']);
        $ad->setBattlesToAward($m['battles_to_award']);
        $ad->setFamePointsToImproveAward($m['fame_points_to_improve_award']);
        $ad->setFamePoints($m['fame_points']);
    }
}
