<?php

namespace AppBundle\Repository;

use AppBundle\Entity\EventAccountData;
use Doctrine\ORM\EntityRepository;

/**
 * EventAccountDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAccountDataRepository extends EntityRepository
{
    /*
     * parses $mdata to add them as collection to $clan
     */
    public function setClanMembersFromArray(&$clan, $mdata)
    {
        if (count($mdata))
        {
            foreach($mdata as $m)
            {
                $ad = new EventAccountData();
                $ad->setAccountId($m->account_id);
                $ad->setAccountName($m->account_name);
                $d = new \DateTime();
                $d->setTimestamp($m->joined_at);
                $ad->setJoinedAt($d);
                $ad->setClan($clan);

                $clan->addMember($ad);
            }
        }

        return;
    }
}
