<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getActiveEvent()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT e
                FROM AppBundle:Event e
                WHERE p.status = "ACTIVE"
            ');

    }

    public function isActiveEvent()
    {
        return ($this->findOneByStatus('ACTIVE')?:false);
/*        $event = $this->findOneByStatus('ACTIVE');
        if(!$event)
            return false;
        else
            return $event;*/
    }
}
